name: Backend CI

on:
  push:
    paths:
      - 'apps/backend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm -w apps/backend run build
      - run: |
          npm -w apps/backend run db:push
          npm -w apps/backend test
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
          SUPABASE_URL: https://example.com
          SUPABASE_API_KEY: test

