name: Frontend CI

on:
  push:
    paths:
      - 'apps/frontend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/frontend-ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm -w apps/frontend run build
      - run: npm -w apps/frontend test
        env:
          VITE_API_BASE_URL: http://localhost:3000
          VITE_SUPABASE_PROJECT: test
          VITE_SUPABASE_API_KEY: test
